# Generated by Django 4.2.14 on 2024-08-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='bookW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Writer', models.CharField(max_length=200)),
                ('vote', models.IntegerField(default=0)),
                ('bookt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookt')),
            ],
        ),
    ]
