# Generated by Django 4.2.14 on 2024-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_person_age_alter_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('birthdate', models.CharField(max_length=8)),
            ],
        ),
    ]
