# Generated by Django 4.2.14 on 2024-08-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_comment_comment_reply_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='book.comment_reply'),
        ),
    ]
