# Generated by Django 4.2.14 on 2024-08-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_comment_reply_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='book.comment'),
        ),
    ]
