# Generated by Django 4.2.14 on 2024-08-26 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_alter_comment_reply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_information',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_information',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
