# Generated by Django 4.2.14 on 2024-08-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_post_information_like_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_information',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.user_information'),
        ),
        migrations.AlterField(
            model_name='post_information',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='post_like_user', to='book.user_information'),
        ),
    ]
