# Generated by Django 4.2.14 on 2024-08-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_post_information_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_information',
            name='like_users',
        ),
    ]
