# Generated by Django 4.2.14 on 2024-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_post_information_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_information',
            name='like_users',
            field=models.ManyToManyField(blank=True, default=1, related_name='post_like_user', to='book.user_information'),
        ),
    ]
