# Generated by Django 4.2.14 on 2024-08-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_post_information_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_users',
            field=models.ManyToManyField(blank=True, default=1, related_name='comment_like_user', to='book.user_information'),
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='commentR_like_users',
            field=models.ManyToManyField(blank=True, default=1, related_name='commentR_like_user', to='book.user_information'),
        ),
    ]
